Belen serer locc
belenserer/challenge-cripto-react-native pull request #1
Opened 2022-10-20 14:35 UTC by belenserer

I created a color theme, deleted some comments and empty components and now I am trying to do the PR from my repo

2022-10-20 16:10 UTC, thom-as-thom requested changes

2022-10-20 16:10 UTC, thom-as-thom commented on Challenge/src/components/ListOfCrypto.tsx
> +    return (
use implicit return

2022-10-20 16:10 UTC, thom-as-thom commented on Challenge/src/components/ListOfCrypto.tsx
> +        <View style={styles.container}>
It's a good idea to use safe area view.

2022-10-20 16:10 UTC, thom-as-thom commented on Challenge/src/components/ListOfCrypto.tsx
> +                        <View style={styles.crypoProfile}>
Crypto profile could be a component

2022-10-20 16:13 UTC, thom-as-thom commented on Challenge/src/components/ListOfCrypto.tsx
> +import React, { useEffect, useState } from "react";
dete unused imports

2022-10-20 22:24 UTC, tomasdematos commented on Challenge/src/components/ListOfCrypto.tsx
> +            {list.map(c => (
use FlatLIst,

2022-11-10 10:40 UTC, tomasdematos commented on App.tsx
> +const App = () => {
use implicit return 
const App = () => ()

2022-11-10 10:41 UTC, tomasdematos commented on App.tsx
> +
delete blank spaces

2022-11-10 10:43 UTC, tomasdematos commented on config/utils/themes.ts
> +const Blue = '#385775'
the format should be : 
```
const theme = {
  colors: {
     black: '#000000',
     .....
  }
}

export default theme;
```

and delete all the const

2022-11-10 10:45 UTC, tomasdematos commented on src/components/cryptoList.tsx
> +        keyExtractor={item => item.id}
you can use destructuring; 

```
keyExtractor={{id] => id}
```

2022-11-10 10:50 UTC, tomasdematos commented on src/components/list.tsx
> +import greenarrow from './img/greenarrow.png';
use PascalCase: 
GreenArrow, RedArrow

2022-11-10 10:54 UTC, tomasdematos commented on src/components/list.tsx
> +            {item.percent > 0 ? (
redundant validation: 
you shoud use one component for this:
```
                <Arrow source={item.percent > 0  ? greenarrow  : redarrow } />
                <TextPercentage positive={item.percent > 0}> {item.percent}% </TextPercentage>
 ```
 
 Styled-components can take props, so you can validate the color dynamically inside the style

2022-11-10 10:54 UTC, tomasdematos commented on src/components/list.tsx
> +
delete black spaces, only use one of is necessary

2022-11-10 10:55 UTC, tomasdematos commented on src/components/styles/stylesCryptoList.ts
> +
delete blank lines, and add a space between this and the next style

2022-11-10 10:55 UTC, tomasdematos commented on src/components/styles/stylesList.ts
> +
delete blank line

2022-11-10 10:57 UTC, tomasdematos commented on src/components/styles/stylesList.ts
> +export const TextPercent = styled(TextRN)`
add a empty space

2022-11-10 10:57 UTC, tomasdematos commented on src/components/styles/stylesList.ts
> +
delete this line

2022-11-10 10:57 UTC, tomasdematos commented on src/components/styles/stylesList.ts
> +
delete this lines

2022-11-10 10:58 UTC, tomasdematos commented on src/components/styles/stylesList.ts
> +
delete blank line

2022-11-10 19:03 UTC, thom-as-thom commented on src/components/cryptoList/index.tsx
> +import {TouchableOpacity, FlatList} from 'react-native';
delete unnecessary imports

2022-11-10 19:11 UTC, belenserer commented on src/components/cryptoList/index.tsx
> +import {TouchableOpacity, FlatList} from 'react-native';
React is unnecesary? I am using TouchableOpacity and FlatList

2022-11-10 19:27 UTC, merged